name: Build NodeJS App

on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        export CI=false
        npm install
        npm run build

    - name: Deploy
      run: |
        # Remove the existing contents of the main branch
        git checkout main
        git rm -r -f ./build  # Use -f to force removal
        
        # Create the build directory if it doesn't exist
        mkdir -p build/
        
        # Copy the build output into the main branch
        cp -r build/* ./build
    
        # Configure Git with the PAT secret
        git config --global credential.helper store
        git config --global user.email "scansioquielom@gmail.com"
        git config --global user.name "Emmanuel Elom"
    
        # Commit the changes
        git add .
        git commit -m "Deploy build output"
    
        # Push the changes using the PAT secret for authentication
        git push https://github.com/$GITHUB_REPOSITORY.git HEAD:main
